<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JobSeek.Prompter.Contracts</RootNamespace>
    <AssemblyName>JobSeek.Prompter.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobSeek.Categorizator.Contracts\JobSeek.Categorizator.Contracts.csproj" />
  </ItemGroup>

</Project>
