<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Comparator</RootNamespace>
    <AssemblyName>Comparator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Categorizator\Categorizator.csproj" />
  </ItemGroup>

</Project>
